# Generated by Django 3.2.12 on 2022-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('Berat', 'Berat'), ('Dibër', 'Dibër'), ('Durrës', 'Durrës'), ('Elbasan', 'Elbasan'), ('Fier', 'Fier'), ('Girokastër', 'Girokastër'), ('Korçë', 'Korçë'), ('Kukës', 'Kukës'), ('Lezhë', 'Lezhë'), ('Shkodër', 'Shkodër'), ('Tiranë', 'Tiranë'), ('Vlorë', 'Vlorë')], default='Tiranë', max_length=50),
        ),
    ]
