# Generated by Django 3.2.12 on 2022-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20220513_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
