# Generated by Django 3.2.12 on 2022-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='unique_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
