# Generated by Django 3.2.12 on 2022-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description_in_english',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_in_english',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.IntegerField(),
        ),
    ]
