# Generated by Django 3.2.12 on 2022-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20220513_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location_link',
            field=models.TextField(blank=True),
        ),
    ]
