# Generated by Django 3.2.12 on 2022-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20220717_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location_link',
            field=models.TextField(blank=True, default="https://www.google.com/maps/place/41%C2%B012'40.3%22N+19%C2%B031'10.6%22E/@41.2111862,19.5174121,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x605debbc8ae35cf4!8m2!3d41.2111862!4d19.5196008?hl=en"),
        ),
    ]
