bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
    }

price_choices = {
    '100000': '€ 100,000',
    '200000': '€ 200,000',
    '300000': '€ 300,000',
    '400000': '€ 400,000',
    '500000': '€ 500,000',
    '600000': '€ 600,000',
    '700000': '€ 700,000',
    '800000': '€ 800,000',
    '900000': '€ 900,000',
    '1000000': '€ 1M+',
}

city_choices = {
    'Tiranë': 'Tiranë',
    'Durrës': 'Durrës',
    'Kamëz': 'Kamëz',
    'Kavajë': 'Kavajë',
    'Rrogozhinë': 'Rrogozhinë',
    'Vorë': 'Vorë',
    'Krujë': 'Krujë',
    'Shijak': 'Shijak',
    'Berat': 'Berat',
    'Kuçovë': 'Kuçovë',
    'Poliçan': 'Poliçan',
    'Skrapar': 'Skrapar',
    'Ura Vajgurore': 'Ura Vajgurore',
    'Bulqizë': 'Bulqizë',
    'Dibër': 'Dibër',
    'Klos': 'Klos',
    'Mat': 'Mat',
    'Belsh': 'Belsh',
    'Cërrik': 'Cërrik',
    'Elbasan': 'Elbasan',
    'Gramsh': 'Gramsh',
    'Librazhd': 'Librazhd',
    'Peqin': 'Peqin',
    'Prrenjas': 'Prrenjas',
    'Fier': 'Fier',
    'Lushnjë,': 'Lushnjë,',
    'Mallakastër': 'Mallakastër',
    'Patos': 'Patos',
    'Roskovec': 'Roskovec',
    'Divjakë': 'Divjakë',
    'Dropull': 'Dropull',
    'Gjirokastër': 'Gjirokastër',
    'Këlcyrë': 'Këlcyrë',
    'Libohovë': 'Libohovë',
    'Memaliaj': 'Memaliaj',
    'Përmet': 'Përmet',
    'Tepelenë': 'Tepelenë',
    'Devoll': 'Devoll',
    'Kolonjë': 'Kolonjë',
    'Korçë': 'Korçë',
    'Maliq': 'Maliq',
    'Pustec': 'Pustec',
    'Pogradec': 'Pogradec',
    'Has': 'Has',
    'Kukës': 'Kukës',
    'Tropojë': 'Tropojë',
    'Kurbin': 'Kurbin',
    'Lezhë': 'Lezhë',
    'Mirditë': 'Mirditë',
    'Fushë-Arrëz': 'Fushë-Arrëz',
    'Malësi e Madhe': 'Malësi e Madhe',
    'Pukë': 'Pukë',
    'Shkodër': 'Shkodër',
    'Vau i Dejës': 'Vau i Dejës',
    'Vlorë': 'Vlorë',
    'Selenicë': 'Selenicë',
    'Sarandë': 'Sarandë',
    'Konispol': 'Konispol',
    'Himarë': 'Himarë',
    'Delvinë': 'Delvinë',
    'Finiq': 'Finiq',

    }

shitje_qera_choices = {
    'Shitje': 'Shitje',
    'Qera': 'Qera',
    'Shitje/Qera': 'Shitje/Qera'
}